"""Download Google Fonts with clean names + generate fonts.css"""
import os, re, sys
import urllib.request

PROXY = "http://localhost:7897"
FONTS_DIR = os.path.join(os.path.dirname(__file__), "..", "web", "public", "fonts")
os.makedirs(FONTS_DIR, exist_ok=True)

opener = urllib.request.build_opener(
    urllib.request.ProxyHandler({"http": PROXY, "https": PROXY})
)

def dload(url, path):
    data = opener.open(url, timeout=60).read()
    with open(path, "wb") as f:
        f.write(data)
    return len(data)

def google_font_css(family, path, dir):
    """Download Google Fonts CSS for a family and return the CSS text."""
    url = f"https://fonts.googleapis.com/css2?family={family}&display=swap"
    data = opener.open(url, timeout=60).read()
    css_text = data.decode("utf-8")
    # Save raw CSS for reference
    with open(os.path.join(dir, path), "w", encoding="utf-8") as f:
        f.write(css_text)
    return css_text

def parse_and_download(css_text, family_slug, dir):
    """Parse CSS @font-face blocks and download font files."""
    blocks = re.findall(
        r"@font-face\s*\{([^}]+)\}", css_text, re.DOTALL
    )
    rules = []
    for block in blocks:
        props = {}
        for m in re.finditer(r"(\w[\w-]*)\s*:\s*(.+?)\s*(?:;|$)", block):
            props[m.group(1).strip()] = m.group(2).strip()

        src = props.get("src", "")
        m = re.search(r"url\(([^)]+)\)", src)
        if not m:
            continue
        url = m.group(1)
        weight = props.get("font-weight", "400")
        style = props.get("font-style", "normal")
        ext = url.rsplit(".", 1)[-1]
        fname = f"{family_slug}-{weight}{'-italic' if style=='italic' else ''}.{ext}"
        fpath = os.path.join(dir, fname)

        if not os.path.exists(fpath):
            print(f"  DL {fname}")
            dload(url, fpath)
        else:
            print(f"  OK {fname}")

        rules.append(f"""@font-face {{
  font-family: '{family_slug}';
  font-style: {style};
  font-weight: {weight};
  font-display: swap;
  src: url(/fonts/{fname}) format('truetype');
}}""")
    return rules

all_rules = []

print("=== Plus Jakarta Sans ===")
css = google_font_css(
    "Plus+Jakarta+Sans:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700;1,800",
    "plus-jakarta-sans.css", FONTS_DIR
)
all_rules += parse_and_download(css, "plus-jakarta-sans", FONTS_DIR)

print("\n=== Lora ===")
css = google_font_css(
    "Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700",
    "lora.css", FONTS_DIR
)
all_rules += parse_and_download(css, "lora", FONTS_DIR)

# Write combined CSS
css_content = """/*
 * Self-hosted Google Fonts for offline Docker build.
 * Generated by scripts/download-fonts.py
 * Fonts: Plus Jakarta Sans, Lora
 */
:root {
  --font-sans: 'plus-jakarta-sans', system-ui, sans-serif;
  --font-serif: 'lora', Georgia, serif;
}
""" + "\n\n".join(all_rules)

css_path = os.path.join(FONTS_DIR, "fonts.css")
with open(css_path, "w", encoding="utf-8") as f:
    f.write(css_content)
print(f"\nWritten: {css_path}")

# Show file sizes
total = 0
for f in sorted(os.listdir(FONTS_DIR)):
    sz = os.path.getsize(os.path.join(FONTS_DIR, f))
    print(f"  {f:60s} {sz:>8,} bytes")
    total += sz
print(f"{'TOTAL':60s} {total:>8,} bytes")
